export enum OrderStatus {
  PENDING = 'PENDING',
  SHIPPED = 'SHIPPED',
  UNPAID = 'UNPAID',
  SPAM = 'SPAM',
  COMPLETED = 'COMPLETED',
}


export enum OrderBusinessStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  SPAM = 'SPAM',
}

export enum OrderPaymentStatus {
  UNKNOWN = 'UNKNOWN',
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  COD_PENDING = 'COD_PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
}

export enum OrderFulfillmentStatus {
  UNKNOWN = 'UNKNOWN',
  UNFULFILLED = 'UNFULFILLED',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RETURNING = 'RETURNING',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum EcomEntityType {
  ORDER = 'order',
  PRODUCT = 'product',
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DRAFT = 'DRAFT',
}

export enum CustomFieldDataType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  LIST = 'LIST',
  BOOLEAN = 'BOOLEAN',
}