import { Injectable } from '@nestjs/common'

import type {
  AiGatewayHealth,
  AiImageEditRequest,
  AiImageRequest,
  AiImageResult,
  AiListModelsRequest,
  AiModel,
  AiProviderGateway,
  AiTextRequest,
  AiTextResult,
  AiVideoRequest,
  AiVideoResult,
} from './ai-provider-gateway.types'

@Injectable()
export class FakeAiProviderGateway implements AiProviderGateway {
  async generateText(request: AiTextRequest): Promise<AiTextResult> {
    const userPrompt = request.messages
      .filter((message) => message.role === 'user')
      .map((message) => message.content)
      .join('\n\n')

    return {
      text: this.buildHtml(userPrompt),
      usage: {
        inputTokens: Math.ceil(userPrompt.length / 4),
        outputTokens: 240,
        estimatedCost: 0,
        currency: 'USD',
      },
      trace: {
        gateway: 'fake',
        provider: 'fake',
        model: request.modelHint ?? 'fake-html-generator',
        latencyMs: 0,
        fallbackAttempts: 0,
      },
      warnings: ['FakeAiProviderGateway generated deterministic local HTML'],
    }
  }

  async generateImage(request: AiImageRequest): Promise<AiImageResult> {
    return {
      assets: [
        {
          assetId: `fake-image-${request.invocationId}`,
          mimeType: 'image/png',
          width: 1024,
          height: 1024,
        },
      ],
      usage: { estimatedCost: 0, currency: 'USD' },
      trace: {
        gateway: 'fake',
        provider: 'fake',
        model: request.modelHint ?? 'fake-image-generator',
        latencyMs: 0,
        fallbackAttempts: 0,
      },
      warnings: ['Fake image placeholder generated'],
    }
  }

  async editImage(request: AiImageEditRequest): Promise<AiImageResult> {
    return this.generateImage({
      ...request,
      capability: 'image',
      count: 1,
      prompt: request.prompt,
    })
  }

  async generateVideo(request: AiVideoRequest): Promise<AiVideoResult> {
    return {
      jobId: `fake-video-${request.invocationId}`,
      status: 'queued',
      usage: { estimatedCost: 0, currency: 'USD' },
      trace: {
        gateway: 'fake',
        provider: 'fake',
        model: request.modelHint ?? 'fake-video-generator',
        latencyMs: 0,
        fallbackAttempts: 0,
      },
      warnings: ['Video generation is queued in fake mode only'],
    }
  }

  async listModels(_request?: AiListModelsRequest): Promise<AiModel[]> {
    return [
      { id: 'fake-html-generator', provider: 'fake', capabilities: ['text'] },
      { id: 'fake-image-generator', provider: 'fake', capabilities: ['image', 'image_edit'] },
    ]
  }

  async healthCheck(): Promise<AiGatewayHealth> {
    return {
      ok: true,
      gateway: 'fake',
      availableCapabilities: ['text', 'image', 'image_edit'],
    }
  }

  private buildHtml(prompt: string): string {
    const escapedPrompt = this.escapeHtml(prompt || 'Landing page generated by fake gateway.')
    return `<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>LadiPage AI Draft</title>
  <style>
    body { margin: 0; font-family: Inter, Arial, sans-serif; color: #111827; background: #f9fafb; }
    main { max-width: 1040px; margin: 0 auto; padding: 56px 20px; }
    h1 { font-size: 44px; line-height: 1.1; margin: 0 0 16px; }
    p { font-size: 18px; line-height: 1.7; color: #4b5563; }
    .cta { display: inline-block; margin-top: 24px; padding: 14px 22px; border-radius: 8px; background: #2563eb; color: white; text-decoration: none; font-weight: 700; }
    section { margin-top: 40px; padding-top: 24px; border-top: 1px solid #e5e7eb; }
  </style>
</head>
<body>
  <main>
    <h1>LadiPage AI Draft</h1>
    <p>${escapedPrompt}</p>
    <a class="cta" href="#contact">Dang ky tu van</a>
    <section id="contact">
      <h2>Thong tin lien he</h2>
      <p>Form lead se duoc gan trong buoc materialize/publish.</p>
    </section>
  </main>
</body>
</html>`
  }

  private escapeHtml(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;')
  }
}
