import { ApiPropertyOptional } from '@nestjs/swagger'
import { IsOptional, IsString, MaxLength } from 'class-validator'

export class CreateOrderPaymentDto {
  @ApiPropertyOptional({ description: 'Stable retry key generated by the caller' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  idempotencyKey?: string
}
