/* eslint-disable */
// Generated from tools/cdp-reverse-engineer/output/merged/schema-tables-merged.json.
// Do not add fields by hand; update CDP artifacts and rerun export:ts-types.

import type { LadipageJsonObject } from '../common';

/**
 * Source routes:
 * - POST apiv5.sales.ldpform.net/2.0/order/list-order
 * - POST apiv5.sales.ldpform.net/2.0/order/show
 */
export interface LpOrder {
  'accept_policy'?: unknown | null;
  'ad_id'?: unknown | null;
  'assignee_id'?: string;
  'billing_address'?: string;
  'billing_apartment'?: unknown | null;
  'billing_company'?: unknown | null;
  'billing_company_address'?: unknown | null;
  'billing_country_code'?: string;
  'billing_country_name'?: string;
  'billing_district_id'?: unknown | null;
  'billing_district_name'?: unknown | null;
  'billing_email'?: unknown | null;
  'billing_first_name'?: string;
  'billing_last_name'?: unknown | null;
  'billing_phone'?: string;
  'billing_postal_code'?: unknown | null;
  'billing_state_id'?: unknown | null;
  'billing_state_name'?: unknown | null;
  'billing_tax_code'?: unknown | null;
  'billing_ward_id'?: unknown | null;
  'billing_ward_name'?: unknown | null;
  'canceled_at'?: unknown | null;
  'created_at'?: string;
  'creator_id'?: string;
  'custom_fields'?: unknown[];
  'customer_email'?: string;
  'customer_first_name'?: string;
  'customer_id'?: number;
  'customer_last_name'?: string;
  'customer_phone'?: string;
  'customer_total_order'?: number;
  'data_fbc'?: unknown | null;
  'data_fbp'?: unknown | null;
  'discount_code'?: unknown | null;
  'discount_fee'?: number;
  'discount_id'?: unknown | null;
  'discount_maximum'?: unknown | null;
  'discount_note'?: unknown | null;
  'discount_shipping_code'?: unknown | null;
  'discount_shipping_fee'?: number;
  'discount_shipping_id'?: unknown | null;
  'discount_shipping_maximum'?: unknown | null;
  'discount_shipping_type'?: unknown | null;
  'discount_shipping_value'?: number;
  'discount_type'?: unknown | null;
  'discount_value'?: number;
  'event_id'?: unknown | null;
  'fb_id'?: unknown | null;
  'gateway_transaction_id'?: string;
  'ip'?: unknown | null;
  'is_auto_shipping'?: number;
  'is_delete'?: number;
  'is_draft'?: number;
  'is_export_invoice'?: number;
  'is_generate_checkout'?: number;
  'is_show'?: number;
  'is_subtract_inventory'?: number;
  'ladi_fb_page_id'?: unknown | null;
  'ladi_fb_psid'?: unknown | null;
  'ladifd'?: unknown | null;
  'mark_spam'?: number;
  'msg_id'?: unknown | null;
  'name'?: string;
  'note'?: string;
  'order_details'?: unknown[];
  'order_id'?: number;
  'order_paid'?: number;
  'ordered_at'?: string;
  'package_discount_note'?: unknown | null;
  'package_discount_price'?: number;
  'package_discount_type'?: unknown | null;
  'package_discount_value'?: unknown | null;
  'page_checkout_id'?: unknown | null;
  'paid'?: number;
  'paid_at'?: string;
  'parent_id'?: unknown | null;
  'parent_reference_no'?: unknown | null;
  'payment_action_type'?: string;
  'payment_api_response'?: unknown | null;
  'payment_callback_params'?: unknown | null;
  'payment_id'?: number;
  'payment_installment_month'?: unknown | null;
  'payment_method'?: string;
  'payment_retry_get_status'?: number;
  'payment_status'?: string;
  'payment_type'?: string;
  'product_type'?: string;
  'ref'?: unknown | null;
  'reference_no'?: string;
  'refund'?: unknown | null;
  'refunded_at'?: unknown | null;
  'restock_all'?: number;
  'shipping_address'?: string;
  'shipping_apartment'?: unknown | null;
  'shipping_company'?: unknown | null;
  'shipping_country_code'?: string;
  'shipping_country_name'?: string;
  'shipping_district_id'?: unknown | null;
  'shipping_district_name'?: unknown | null;
  'shipping_fee'?: number;
  'shipping_first_name'?: string;
  'shipping_last_name'?: unknown | null;
  'shipping_note'?: unknown | null;
  'shipping_phone'?: string;
  'shipping_postal_code'?: unknown | null;
  'shipping_rate_detail_id'?: unknown | null;
  'shipping_rate_name'?: unknown | null;
  'shipping_rate_type'?: unknown | null;
  'shipping_refund'?: number;
  'shipping_state_id'?: unknown | null;
  'shipping_state_name'?: unknown | null;
  'shipping_status'?: string;
  'shipping_ward_id'?: unknown | null;
  'shipping_ward_name'?: unknown | null;
  'shippings'?: unknown[];
  'source'?: string;
  'status'?: string;
  'store_id'?: number;
  'store_name'?: unknown | null;
  'sub_total'?: number;
  'sync_from'?: unknown | null;
  'sync_order_id'?: unknown | null;
  'sync_time'?: unknown | null;
  'tag_colors'?: string;
  'tag_ids'?: string;
  'tag_names'?: string;
  'tags'?: unknown[];
  'tax_fee'?: number;
  'thank_url'?: unknown | null;
  'total'?: number;
  'total_child'?: number;
  'tracking_script'?: unknown | null;
  'transaction_id'?: string;
  'transaction_status_id'?: unknown | null;
  'updated_at'?: unknown | null;
  'url_page'?: unknown | null;
  'user_agent'?: unknown | null;
  'utm_campaign'?: unknown | null;
  'utm_content'?: unknown | null;
  'utm_medium'?: unknown | null;
  'utm_source'?: unknown | null;
  'utm_term'?: unknown | null;
  'va_number'?: unknown | null;
  'weight'?: number;
}
